version: '3.9'

services:
  database:
    image: postgres
    container_name: todoPostgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=todoPostgres
      - POSTGRES_DB=todoPostgres
    volumes:
     - pgdata:/data/postgres

volumes: 
  pgdata:
    driver: local